apiVersion: v2
name: costfluent-k8s-agent
description: Reports Kubernetes usage to Costfluent for cost allocation by cluster, namespace and label
type: application
version: 0.2.0
appVersion: "0.2.0"
keywords:
  - kubernetes
  - cost
  - finops
home: https://docs.costfluent.com/connect/kubernetes
icon: https://costfluent.com/favicon/favicon.svg
sources:
  - https://github.com/costfluent/helm-charts
  - https://github.com/costfluent/k8s-agent
maintainers:
  - name: Costfluent
    email: support@costfluent.com
