{{- if and .Values.agent.token (not .Values.agent.secret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "costfluent-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "costfluent-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.agent.token | quote }}
{{- end }}
